version: "3.3"
services:

  web:
    image: php:apache
    ports:
    - 80:80
    volumes:
    - ./:/var/www/html
    links:
    - db

  db:
    image: mysql:5.6
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: very_strong_password
    volumes:
    - ./Docker/mysql:/var/lib/mysql
    - ./Docker/mysql-initdb:/docker-entrypoint-initdb.d
